const REQUEST_REDUCER_IDENTIFIER = 'REQUEST_REDUCER';

const NOT_STARTED = 'NOT_STARTED';
const PENDING = 'PENDING';
const SUCCESS = 'SUCCESS';
const FAILURE = 'FAILURE';

const status = {
  NOT_STARTED,
  PENDING,
  SUCCESS,
  FAILURE,
};

export {
  REQUEST_REDUCER_IDENTIFIER,
  status,
};
